# Generated by Django 5.2.1 on 2025-06-09 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Additive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("additive_name", models.CharField(max_length=50)),
                ("additive_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "additives",
            },
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_name", models.CharField(max_length=100)),
                (
                    "broker_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "brokers",
            },
        ),
        migrations.CreateModel(
            name="Commodity_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_group_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Commodity Group",
                "verbose_name_plural": "Commodity Groups",
                "db_table": "commodity_groups",
            },
        ),
        migrations.CreateModel(
            name="Commodity_Subtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_subtype_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Commodity Subtype",
                "verbose_name_plural": "Commodity Subtypes",
                "db_table": "commodity_subtypes",
            },
        ),
        migrations.CreateModel(
            name="Commodity_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_type_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Commodity Type",
                "verbose_name_plural": "Commodity Types",
                "db_table": "commodity_types",
            },
        ),
        migrations.CreateModel(
            name="Cost_Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_center_name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Cost Center",
                "verbose_name_plural": "Cost Centers",
                "db_table": "cost_centers",
            },
        ),
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counterparty_name", models.CharField(max_length=100)),
                (
                    "counterparty_code",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                ("tax_id", models.CharField(blank=True, max_length=30)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("is_supplier", models.BooleanField(default=False)),
                ("is_customer", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Counterparties",
                "db_table": "counterparties",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.CharField(max_length=3, unique=True)),
                ("currency_name", models.CharField(max_length=50)),
                ("currency_symbol", models.CharField(blank=True, max_length=5)),
            ],
            options={
                "verbose_name_plural": "Currencies",
                "db_table": "currencies",
            },
        ),
        migrations.CreateModel(
            name="Delivery_Format",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_format_name", models.CharField(max_length=50)),
                (
                    "delivery_format_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Delivery Format",
                "verbose_name_plural": "Delivery Formats",
                "db_table": "delivery_formats",
            },
        ),
        migrations.CreateModel(
            name="ICOTERM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icoterm_name", models.CharField(max_length=50)),
                ("icoterm_code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "ICOTERM",
                "verbose_name_plural": "ICOTERMS",
                "db_table": "icoterms",
            },
        ),
        migrations.CreateModel(
            name="Sociedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sociedad_name", models.CharField(max_length=50)),
                ("tax_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Sociedades",
                "db_table": "sociedades",
            },
        ),
        migrations.CreateModel(
            name="Trade_Operation_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_operation_type_name", models.CharField(max_length=50)),
                (
                    "operation_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Trade Operation Type",
                "verbose_name_plural": "Trade Operation Types",
                "db_table": "trade_operation_types",
            },
        ),
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trader_name", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "traders",
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commodity_name_short", models.CharField(max_length=50)),
                ("commodity_name_full", models.CharField(blank=True, max_length=200)),
                ("unit_of_measure", models.CharField(default="MT", max_length=20)),
                (
                    "commodity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_group",
                    ),
                ),
                (
                    "commodity_subtype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_subtype",
                    ),
                ),
                (
                    "commodity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nextcrm.commodity_type",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Commodities",
                "db_table": "commodities",
            },
        ),
        migrations.CreateModel(
            name="Counterparty_Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("counterparty_facility_name", models.CharField(max_length=100)),
                ("facility_type", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="nextcrm.counterparty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Counterparty Facility",
                "verbose_name_plural": "Counterparty Facilities",
                "db_table": "counterparty_facilities",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("broker_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("freight_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("forex", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("payment_days", models.IntegerField()),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=15),
                ),
                ("unit_of_measure", models.CharField(default="MT", max_length=20)),
                ("entrega", models.CharField(max_length=200)),
                ("delivery_period", models.DateField()),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("executed", "Executed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "additive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.additive",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="nextcrm.broker"
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.commodity",
                    ),
                ),
                (
                    "commodity_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.commodity_group",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.cost_center",
                    ),
                ),
                (
                    "counterparty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.counterparty",
                    ),
                ),
                (
                    "broker_fee_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="broker_fee_contracts",
                        to="nextcrm.currency",
                    ),
                ),
                (
                    "trade_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trade_contracts",
                        to="nextcrm.currency",
                    ),
                ),
                (
                    "delivery_format",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.delivery_format",
                    ),
                ),
                (
                    "icoterm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.icoterm",
                    ),
                ),
                (
                    "sociedad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.sociedad",
                    ),
                ),
                (
                    "trade_operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="nextcrm.trade_operation_type",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="nextcrm.trader"
                    ),
                ),
            ],
            options={
                "db_table": "contracts",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "date"], name="contracts_status_0d157b_idx"
                    ),
                    models.Index(
                        fields=["trader", "date"], name="contracts_trader__61793e_idx"
                    ),
                    models.Index(
                        fields=["counterparty", "date"],
                        name="contracts_counter_12f034_idx",
                    ),
                ],
            },
        ),
    ]
