# Generated by Django 5.2.1
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nextcrm', '0002_fix_commodity_relationships'),
    ]

    operations = [
        # Add created_at and updated_at fields to existing models
        # Using timezone.now() as default for existing records
        
        migrations.AddField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='cost_center',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cost_center',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='trader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='commodity_group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity_group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='commodity_type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity_type',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='commodity_subtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity_subtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='commodity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='counterparty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='broker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='icoterm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icoterm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='delivery_format',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_format',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='additive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='sociedad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociedad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        migrations.AddField(
            model_name='trade_operation_type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade_operation_type',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Create the new Trade_Setting model
        migrations.CreateModel(
            name='Trade_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trade Setting',
                'verbose_name_plural': 'Trade Settings',
                'db_table': 'trade_settings',
                'ordering': ['setting_name'],
            },
        ),
    ]