# Generated by Django 5.2.1 on 2025-06-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0003_add_audit_fields_and_trade_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contract",
            name="commodity_group",
        ),
    ]
