# Generated by Django 5.2.1 on 2025-06-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0004_remove_contract_commodity_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty",
            name="counterparty_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="counterparty",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_customer", True), ("is_supplier", True), _connector="OR"
                ),
                name="counterparty_must_be_customer_or_supplier",
            ),
        ),
    ]
