# Generated by NextCRM automation to add safe per-year contract number allocator

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0005_alter_counterparty_counterparty_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractNumberSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True)),
                ("last_number", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "contract_number_sequences",
                "verbose_name": "Contract Number Sequence",
                "verbose_name_plural": "Contract Number Sequences",
            },
        ),
    ]

