# Generated by Django 5.2.1 on 2025-08-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0005_alter_counterparty_counterparty_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commodity_type",
            name="commodity_group",
        ),
    ]
