# Generated by NextCRM automation: add contacts model linked to counterparty

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0006_contract_number_sequence"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=50)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("lead", "Lead")], default="lead", max_length=10)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_contact", models.DateTimeField(blank=True, null=True)),
                ("counterparty", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="nextcrm.counterparty")),
            ],
            options={
                "db_table": "contacts",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["counterparty", "status"], name="nextcrm_con_counter_335a4f_idx"),
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(fields=["email"], name="nextcrm_con_email_3a4e25_idx"),
        ),
    ]

