# Generated by Django 5.2.1 on 2025-08-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0006_remove_commodity_group_from_type"),
    ]

    operations = [
        # Add is_active field to Counterparty (set to True by default)
        migrations.AddField(
            model_name='counterparty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        
        # Add many-to-many relationship to commodity types
        migrations.AddField(
            model_name='counterparty',
            name='commodity_types',
            field=models.ManyToManyField(blank=True, related_name='counterparties', to='nextcrm.commodity_type'),
        ),
        
        # Remove the constraint first (it references the fields we're about to remove)
        migrations.RemoveConstraint(
            model_name='counterparty',
            name='counterparty_must_be_customer_or_supplier',
        ),
        
        # Remove is_supplier and is_customer fields
        migrations.RemoveField(
            model_name='counterparty',
            name='is_supplier',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='is_customer',
        ),
        
        # Create Contact model
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='nextcrm.counterparty')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
        
        # Add unique constraint for primary contacts
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('counterparty', 'is_primary'), name='unique_primary_contact_per_counterparty'),
        ),
    ]
