# Generated by Django 5.2.1 on 2025-08-14 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0007_update_counterparty_and_add_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trader",
            name="allowed_commodity_types",
            field=models.ManyToManyField(
                blank=True,
                help_text="Commodity types this trader can access",
                related_name="traders",
                to="nextcrm.commodity_type",
            ),
        ),
        migrations.AddField(
            model_name="trader",
            name="allowed_sociedades",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sociedades this trader can access",
                related_name="traders",
                to="nextcrm.sociedad",
            ),
        ),
        migrations.AddField(
            model_name="trader",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trader",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
