# Generated by NextCRM automation: add price_type and side to Trade_Operation_Type

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade_operation_type",
            name="price_type",
            field=models.CharField(choices=[("FLAT", "Flat"), ("UNPRICED", "Unpriced"), ("FUTURES", "Futures")], default="FLAT", max_length=10),
        ),
        migrations.AddField(
            model_name="trade_operation_type",
            name="side",
            field=models.CharField(choices=[("BUY", "Buy"), ("SELL", "Sell")], default="BUY", max_length=4),
        ),
    ]

