# Generated by NextCRM automation: add Deal and DealLine models and link Contract to Deal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0008_add_fields_to_trade_operation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealNumberSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.IntegerField(unique=True)),
                ("last_number", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "deal_number_sequences",
                "verbose_name": "Deal Number Sequence",
                "verbose_name_plural": "Deal Number Sequences",
            },
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deal_number", models.CharField(blank=True, max_length=50, unique=True)),
                ("broker_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("freight_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("forex", models.DecimalField(decimal_places=4, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ("payment_days", models.IntegerField()),
                ("unit_of_measure", models.CharField(default="MT", max_length=20)),
                ("entrega", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("approved", "Approved"), ("executed", "Executed"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additive", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.additive")),
                ("broker", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.broker")),
                ("broker_fee_currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="broker_fee_deals", to="nextcrm.currency")),
                ("commodity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.commodity")),
                ("counterparty", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.counterparty")),
                ("cost_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.cost_center")),
                ("delivery_format", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.delivery_format")),
                ("icoterm", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.icoterm")),
                ("sociedad", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.sociedad")),
                ("trade_currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="trade_deals", to="nextcrm.currency")),
                ("trade_operation_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.trade_operation_type")),
                ("trader", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="nextcrm.trader")),
            ],
            options={
                "db_table": "deals",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_period_start", models.DateField()),
                ("delivery_period_end", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ("sync_status", models.CharField(choices=[("pending", "Pending"), ("generated", "Generated"), ("synced", "Synced"), ("locked", "Locked")], default="pending", max_length=10)),
                ("deal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="nextcrm.deal")),
                ("materialized_contract", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="deal_line", to="nextcrm.contract")),
            ],
            options={
                "db_table": "deal_lines",
                "ordering": ["delivery_period_start"],
            },
        ),
        migrations.AddIndex(
            model_name="dealline",
            index=models.Index(fields=["deal", "delivery_period_start"], name="nextcrm_dea_deal_id_7298b0_idx"),
        ),
        migrations.AddField(
            model_name="contract",
            name="deal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="nextcrm.deal"),
        ),
    ]

