# Generated by NextCRM automation: add override_fields to Contract

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0009_deals_and_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="override_fields",
            field=models.JSONField(blank=True, null=True),
        ),
    ]

