# Generated by Django 5.2.1 on 2025-11-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0014_facility_segment_and_consumption"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contact",
            new_name="contacts_counter_1abb95_idx",
            old_name="nextcrm_con_counter_335a4f_idx",
        ),
        migrations.RenameIndex(
            model_name="contact",
            new_name="contacts_email_2eb381_idx",
            old_name="nextcrm_con_email_3a4e25_idx",
        ),
        migrations.RenameIndex(
            model_name="dealline",
            new_name="deal_lines_deal_id_e25c21_idx",
            old_name="nextcrm_dea_deal_id_7298b0_idx",
        ),
        migrations.AlterField(
            model_name="counterparty_facility",
            name="segment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BAKERY", "Bakery"),
                    ("PASTRY", "Pastry"),
                    ("CANNED_FOOD", "Canned food"),
                    ("BOTTLERS", "Bottlers"),
                    ("MERCHANTS", "Merchants"),
                    ("TECHNICAL", "Technical"),
                    ("SNACKS", "Snacks"),
                    ("FEED", "Feed"),
                    ("BIODIESEL", "Biodiesel"),
                    ("SAUCES_DRESSINGS", "Sauces and dressings"),
                    ("FROZEN_FOODS", "Frozen foods"),
                    ("COSMETICS", "Cosmetics"),
                    ("OLEOCHEMICALS", "Oleochemicals"),
                ],
                max_length=50,
            ),
        ),
    ]
