# Generated by Django 5.2.1 on 2025-11-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0015_monthly_volume_no_decimals"),
        (
            "nextcrm",
            "0015_rename_nextcrm_con_counter_335a4f_idx_contacts_counter_1abb95_idx_and_more",
        ),
    ]

    operations = []
