# Generated by Django 5.2.1 on 2025-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0017_counterparty_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="counterparty_note",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="counterparty_note",
            index=models.Index(
                fields=["counterparty", "-created_at"],
                name="counterpart_counter_d74652_idx",
            ),
        ),
    ]
