# Generated by Django 5.2.1 on 2025-11-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0018_alter_counterparty_note_id_and_more"),
        ("nextcrm", "0018_facility_region_province"),
    ]

    operations = []
