# Generated by Django 5.2.1 on 2025-11-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0019_facility_enrichment_run"),
        ("nextcrm", "0019_merge_20251102_1235"),
    ]

    operations = []
