# Generated by Django 5.2.1 on 2025-11-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0002_contract_delivery_range"),
        ("nextcrm", "0020_merge_20251102_1309"),
    ]

    operations = []
