# Generated by Django 5.2.1 on 2025-11-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nextcrm", "0021_merge_20251102_1927"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="nextcrm.broker",
            ),
        ),
    ]
