# Generated by Django 5.2.1 on 2025-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_auditlog_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_admin",
            field=models.BooleanField(default=False, help_text="Admin privileges flag"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Admin-controlled approval gate"
            ),
        ),
    ]
