# Generated by Django 5.2.1 on 2025-11-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_auditlog_ip_address_and_more"),
        ("authentication", "0002_authz_models"),
    ]

    operations = []
