# Generated by Django 5.2.1 on 2025-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_add_approval_and_admin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_trader",
            field=models.BooleanField(default=False, help_text="User is a trader flag"),
        ),
    ]
