# Generated by Django 5.2.1 on 2025-11-08 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_merge_20251108_1701"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userroleassignment",
            new_name="auth_user_r_user_id_67b32f_idx",
            old_name="authentication_user_idx",
        ),
        migrations.RenameIndex(
            model_name="userroleassignment",
            new_name="auth_user_r_role_id_9bbf78_idx",
            old_name="authentication_role_idx",
        ),
    ]
