# Generated by Django 5.2.1 on 2025-11-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_rename_authentication_user_idx_auth_user_r_user_id_67b32f_idx_and_more",
        ),
        ("authentication", "0004_seed_roles"),
    ]

    operations = []
